name: posix
version: 2.2.3
homepage: https://github.com/bsutton/dart_posix
description: Exposes the POSIX api on OSx and Linux
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies: 
  ffi: ^1.0.0
  meta: ^1.7.0
  quiver: ^3.0.1+1
dev_dependencies: 
  dcli: ^1.14.1
  ffigen: ^2.0.0
  lint_hard: ^1.0.0
  test: ^1.16.2
