name: posix
version: 3.1.0
homepage: https://github.com/bsutton/dart_posix
description: Exposes the POSIX api on OSx and Linux
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  ffi: ^1.1.2
  meta: ^1.7.0
  quiver: ^3.0.1+1
dev_dependencies: 
  dcli: ^1.20.1
  ffigen: ^4.1.2
  lint_hard: ^1.0.0
  test: ^1.16.2
