name: posix
version: 4.2.0
homepage: https://github.com/onepub-dev/dart_posix
description: Exposes the POSIX api on OSx and Linux
environment: 
  sdk: '>=2.16.0 <3.0.0'
dependencies: 
  ffi: ^2.0.1
  meta: ^1.7.0
  path: ^1.8.3
  quiver: ^3.0.1+1
dev_dependencies: 
  dcli: ^2.0.0
  dcli_core: ^2.0.0
  ffigen: ^6.0.0
  lint_hard: ^3.0.0
  test: ^1.16.2
